// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtrdNvmMmTeu4dN452W6hLeLxxQcPgOYw',
    appId: '1:119190373496:web:2098f9c1faff74a406598d',
    messagingSenderId: '119190373496',
    projectId: 'firetasks-ff04c',
    authDomain: 'firetasks-ff04c.firebaseapp.com',
    storageBucket: 'firetasks-ff04c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1OSnEH1u-nndR6eQ38FfXapPvVI-oWvw',
    appId: '1:119190373496:android:bd274c8524bd273c06598d',
    messagingSenderId: '119190373496',
    projectId: 'firetasks-ff04c',
    storageBucket: 'firetasks-ff04c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz_knZ8GYE2QI5nDwVbbCmt-aeaij4Vbc',
    appId: '1:119190373496:ios:09f0b5e9c0658caa06598d',
    messagingSenderId: '119190373496',
    projectId: 'firetasks-ff04c',
    storageBucket: 'firetasks-ff04c.firebasestorage.app',
    iosBundleId: 'com.example.firetasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz_knZ8GYE2QI5nDwVbbCmt-aeaij4Vbc',
    appId: '1:119190373496:ios:09f0b5e9c0658caa06598d',
    messagingSenderId: '119190373496',
    projectId: 'firetasks-ff04c',
    storageBucket: 'firetasks-ff04c.firebasestorage.app',
    iosBundleId: 'com.example.firetasks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtrdNvmMmTeu4dN452W6hLeLxxQcPgOYw',
    appId: '1:119190373496:web:5c1e784ff4a7279606598d',
    messagingSenderId: '119190373496',
    projectId: 'firetasks-ff04c',
    authDomain: 'firetasks-ff04c.firebaseapp.com',
    storageBucket: 'firetasks-ff04c.firebasestorage.app',
  );
}
